# Generated by Django 3.1 on 2020-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
