# Generated by Django 3.1 on 2020-09-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20200911_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.CharField(max_length=50),
        ),
    ]
