# Generated by Django 3.1 on 2020-09-12 03:54

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20200911_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('hw', models.FileField(blank=True, null=True, upload_to=application.models.upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
